//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MSSAJobBoardLoginCapable
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Job
    {
        public int id { get; set; }
        [Display(Name = "Job Title")]
        public string JobTitle { get; set; }
        [Display(Name = "Company Name")]
        public string CompanyName { get; set; }
        [Url]
        [Display(Name = "Job Link (URL)")]
        public string JobLink { get; set; }
        [Display(Name = "Job Description")]
        public string JobDescription { get; set; }
        public Nullable<int> RecruiterId { get; set; }

        
        public Nullable<int> CompanyId { get; set; }

        
        public virtual Company Company { get; set; }
        
        public virtual Recruiter Recruiter { get; set; }
    }
}
