//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MSSAJobBoardLoginCapable
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Recruiter
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Recruiter()
        {
            this.Jobs = new HashSet<Job>();
        }

        [Display(Name = "Recruiter")]
        public int id { get; set; }
        
        [Display(Name = "Full Name")]
        public string FName { get; set; }
        
        [Display(Name = "Last Name")]
        public string LName { get; set; }
        
        [Display(Name = "eMail Address")]
        [EmailAddress]
        public string eMailAddress { get; set; }
        
        [Display(Name = "Phone Number")]
        [PhoneAttribute]
        public string PhoneNumber { get; set; }

        [Display(Name = "LinkedIn")]
        [Url]
        public string LinkedIn { get; set; }
        
        [Display(Name = "Recruiting Agency/Company")]
        public string CompanyName { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Job> Jobs { get; set; }
    }
}
